from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main.views import *



# Bu url  uchun 
urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/slider/", Slider.as_view()),
    path("api/countryView/", CountryView.as_view()),
    path("api/email/", EmailView.as_view()),
    path("api/category/", CategoryView.as_view()),
    path("api/image/", ImageView.as_view()),
    path("api/latestproduct/", latest_products),
    path("api/filterbyprice/",filter_by_price),
    path("api/contactus/",contactus),
    path("api/productdetail/<int:pk>/",ProductDetail.as_view()),
    path("api/reviewget/", RewievGEt.as_view()),
    path("api/reviewpost/", RewievPost.as_view()),
    path("api/card/", CardView.as_view()),
    path("api/cart-total/", total_card),
    path("api/check-out/", CheckOut),
    path("api/wishlist/", WishlistView.as_view()),
    path("api/blog/", BlogView.as_view()),
    path("api/blog-text/", BlogtextView.as_view()),
    path("api/about/", AboutView.as_view()),
    path("api/about-text/", AbouttextView.as_view()),
    path("api/replay/", ReplaySend.as_view()),
    path("api/comment/", CommentSend.as_view()),
    path("login/",Login),
    
    # Templates

    path('home/', Index, name='home'),
    path('product/', Productt, name='product'),
    path('add-product/', AddProductt, name='add-product'),
    path('edit-product/<int:pk>/', EditProductt, name='edit-product'),
    path("product-delete/<int:pk>/", product_delete, name="deleteproduct"),
    path('blog/', blog, name='blog'),
    path('add-blog/', add_blog, name='add-blog'),
    path('edit-blog/<int:pk>/', edit_blog, name='edit-blog'),
    path("blog-delete/<int:pk>/", blog_delete, name="deleteblog"),
    path('about/', about, name='about'),
    path('add-about/', add_about, name='add-about'),
    path('edit-about/<int:pk>/', edit_about, name='edit-about'),
    path("about-delete/<int:pk>/", about_delete, name="deleteabout"),
    path("country/", country, name="country"),
    path('add-country/', add_country, name='add-country'),
    path('edit-country/<int:pk>/', edit_country, name='edit-country'),
    path("country-delete/<int:pk>/", country_delete, name="deletecountry"),
    path("info/", info, name="info"),
    path('add-info/', add_info, name='add-info'),
    path('edit-info/<int:pk>/', edit_info, name='edit-info'),
    path("info-delete/<int:pk>/", info_delete, name="deleteinfo"),
    path("email/", email, name="email"),
    path("email-delete/<int:pk>/", email_delete, name="deleteemail"),
    path("category/", category, name="category"),
    path('add-category/', add_category, name='add-category'),
    path('edit-category/<int:pk>/', edit_category, name='edit-category'),
    path("category-delete/<int:pk>/", category_delete, name="deletecategory"),
    path("image/", imagess, name="image"),
    path('add-image/', add_image, name='add-image'),
    path('edit-image/<int:pk>/', edit_image, name='edit-image'),
    path("image-delete/<int:pk>/", image_delete, name="deleteimage"),
    path("review/", review, name="review"),
    path('add-review/', add_review, name='add-review'),
    path('edit-review/<int:pk>/', edit_review, name='edit-review'),
    path("review-delete/<int:pk>/", review_delete, name="deletereview"),
    path("contactus/", contactus, name="contactus"),
    path("contactus-delete/<int:pk>/", contactus_delete, name="deletecontactus"),
    path("reply/", reply, name="reply"),
    path("reply-delete/<int:pk>/", reply_delete, name="deletereply"),
    path("comment/", comment, name="comment"),
    path("comment-delete/<int:pk>/", comment_delete, name="deletecomment"),
    path("blogtext/", blogtext, name="blogtext"),
    path('add-blogtext/', add_blogtext, name='add-blogtext'),
    path('edit-blogtext/<int:pk>/', edit_blogtext, name='edit-blogtext'),
    path("blogtext-delete/<int:pk>/", blogtext_delete, name="deleteblogtext"),
    path("abouttext/", abouttext, name="abouttext"),
    path('add-abouttext/', add_abouttext, name='add-abouttext'),
    path('edit-abouttext/<int:pk>/', edit_abouttext, name='edit-abouttext'),
    path("abouttext-delete/<int:pk>/", abouttext_delete, name="deleteabouttext"),
    path("delivery_options/", delivery_options, name="delivery_options"),
    path('add-delivery_options/', add_delivery_options, name='add-delivery_options'),
    path('edit-delivery_options/<int:pk>/', edit_delivery_options, name='edit-delivery_options'),
    path("delivery_options-delete/<int:pk>/", delivery_options_delete, name="deletedelivery_options"),
    path("order/", order, name="order"),
    path('add-order/', add_order, name='add-order'),
    path("", web_Login, name="login")
   
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

