# Generated by Django 4.0.6 on 2022-07-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='tw_link',
            new_name='tg_link',
        ),
    ]
