# Generated by Django 4.0.6 on 2022-07-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_tw_link_info_tg_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='tg_link',
            new_name='tw_link',
        ),
    ]
